# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desarrolladora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('precio', models.PositiveIntegerField(default=999, validators=[game.models.value_validator])),
                ('desarrolladora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Desarrolladora')),
            ],
        ),
    ]
